/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.menu.file;

import controller.dao.simpledao.AuthorDao;
import controller.dao.simpledao.BookDao;
import controller.dao.simpledao.GenderDao;
import java.sql.SQLException;
import java.util.List;
import model.dto.BookDTO;
import view.utils.Utils;
import controller.dao.simpledao.SimpleObjDao;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import model.dto.AuthorDTO;
import model.dto.GenderDTO;

/**
 *
 * @author Nana
 */
public class jdBooks extends javax.swing.JDialog {
    private SimpleObjDao simpleObjDao;
    private DefaultComboBoxModel modelCboGenders;
    private DefaultComboBoxModel modelCboAuthors;
    private List <BookDTO> listBooks;
    
    public jdBooks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listBooks = new ArrayList<>();
        fillBooksList();
        fillCboGendersBook();
        fillCboAuthorsBooks();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstBooks = new javax.swing.JList<>();
        txtNameBook = new javax.swing.JTextField();
        cboAuthorsBook = new javax.swing.JComboBox<>();
        cboGendersBook = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstBooks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstBooks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBooksValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstBooks);

        txtNameBook.setText("Nombre del libro");

        cboAuthorsBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aquí todos los autores" }));

        cboGendersBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aquí todos los géneros" }));

        jButton1.setText("Nuevo");

        jButton2.setText("Aceptar");

        jButton3.setText("Modificar");

        jButton4.setText("Cancelar");

        jTextField1.setText("Buscar por nombre ?");

        jButton5.setText("Ir");

        jLabel1.setText("Propiedades del libro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNameBook)
                            .addComponent(cboAuthorsBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboGendersBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAuthorsBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboGendersBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstBooksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstBooksValueChanged

        fillFieldFromJListBooks(lstBooks.getSelectedIndex());
        
    }//GEN-LAST:event_lstBooksValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdBooks dialog = new jdBooks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void fillBooksList () {
        simpleObjDao = new BookDao();
        try {
            listBooks = simpleObjDao.select();
            Utils.fillJList(listBooks, lstBooks);

        } catch (SQLException e) {
            System.out.println("Excepcion en la carga de lista de books");
            e.printStackTrace();
        }    
    }
    
    private void fillCboGendersBook(){
        simpleObjDao = new GenderDao();
        modelCboGenders = new DefaultComboBoxModel();
        try {
            List<GenderDTO> genders = simpleObjDao.select();
            Utils.fillComboBox(modelCboGenders, genders, cboGendersBook);
            
        } catch (Exception e) {
            System.out.println("Excepcion en la carga del combo de genders");
            e.printStackTrace();
        }
                
    }
    
    private void fillCboAuthorsBooks () {
        modelCboAuthors = new DefaultComboBoxModel();
        simpleObjDao = new AuthorDao();
        try {
            List <AuthorDTO> authors = simpleObjDao.select();
            Utils.fillComboBox(modelCboAuthors, authors, cboAuthorsBook);

        } catch (SQLException e) {
            System.out.println("Excepcion en la carga de lista de books");
            e.printStackTrace();
        }      
    }
    
    private void fillFieldFromJListBooks (int i) {
        txtNameBook.setText(listBooks.get(i).getName());
        selectGenderFromJListBooks(listBooks.get(i).getIdGender());
        selectAuthorFromJListBooks(listBooks.get(i).getIdAuthor());
    }
    
    private void selectGenderFromJListBooks(int id){
        for (int i = 0; i < cboGendersBook.getItemCount(); i++) {
            GenderDTO g =  (GenderDTO) modelCboGenders.getElementAt(i);
            if (g.getId() == id){
                cboGendersBook.setSelectedIndex(i);
                return;
            }
        }
    }
    
    private void selectAuthorFromJListBooks(int id){
        for (int i = 0; i < cboAuthorsBook.getItemCount(); i++) {
            AuthorDTO a = (AuthorDTO) modelCboAuthors.getElementAt(id);
            if (a.getId() == id){
                cboAuthorsBook.setSelectedIndex(id);
                return;
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboAuthorsBook;
    private javax.swing.JComboBox<String> cboGendersBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> lstBooks;
    private javax.swing.JTextField txtNameBook;
    // End of variables declaration//GEN-END:variables
}
